version: '3'
services:
  php-apache-environment:
    build:
      context: ./src/web-server/php
      dockerfile: dockerfile
    container_name: php-apache
    image: php:8.0-apache
    volumes:
      - ./src/web-server/data/:/var/www/html/
    ports:
      - 8000:80