#https://blog.devsense.com/2019/php-nginx-docker
version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: images/web-server/dockerfile
    ports: 
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./images/web-server/data/:/var/www/html/
  php:
    image: php:fpm-alpine
    networks:
      - internal
    volumes:
      - ./images/web-server/data/:/var/www/html/
networks:
  internal:
    driver: bridge