apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: secret-sync 
spec:
  vault:
    name: activityplanner # name of key vault
    object:
      name: mysql-password # name of the akv object
      type: secret # akv object type
  output: 
    secret: 
      name: mysql-password # kubernetes secret name
      dataKey: secret-value # key to store object value in kubernetes secret
---