# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: azurefiles
# spec:
#   capacity:
#     storage: 5Gi
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: my-azurefile
#   hostPath:
#     path: /data/azurefiles # You might have to create this manually. 
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - minikube